steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nextjs-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nextjs-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'nextjs-app', '--image', 'gcr.io/$PROJECT_ID/nextjs-app', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']
logsBucket: 'gs://rikishi-445600-cloudbuild-logs'
images:
  - 'gcr.io/$PROJECT_ID/nextjs-app'
